-- ==============================================================================
-- MINDPROTECTION: FULL COMPLETE SUPABASE SQL SCHEMA & AUTO-MIGRATION (v1.0.8)
-- ==============================================================================
-- Run this entire script in your Supabase SQL Editor (SQL -> New Query -> Run).
-- It safely creates all tables from scratch OR automatically upgrades your existing
-- database tables (converting GENERATED ALWAYS to GENERATED BY DEFAULT, fixing
-- screen_times column names, adding constraints, indexes, and RLS policies).
-- ==============================================================================

-- 1. PROFILES TABLE (Core user account details linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text UNIQUE,
  avatar_url text,
  streak_days integer NOT NULL DEFAULT 0,
  focus_score integer NOT NULL DEFAULT 0,
  level integer NOT NULL DEFAULT 1,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. FOCUS SESSIONS TABLE (Pomodoro / Deep Focus activity sync)
CREATE TABLE IF NOT EXISTS public.focus_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  subject text NOT NULL,
  start_time timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 0,
  is_deep_focus boolean NOT NULL DEFAULT false,
  is_completed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. TASKS TABLE (Planner tasks sync)
CREATE TABLE IF NOT EXISTS public.tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  schedule_time timestamp with time zone NOT NULL,
  priority text NOT NULL DEFAULT 'Medium',
  is_completed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. ROUTINES TABLE (Morning / Afternoon / Night routines sync)
CREATE TABLE IF NOT EXISTS public.routines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  time_of_day text NOT NULL, -- 'Morning', 'Afternoon', or 'Night'
  is_completed boolean NOT NULL DEFAULT false,
  last_checked timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. GOALS TABLE (Short-term and Long-term goals sync)
CREATE TABLE IF NOT EXISTS public.goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  is_long_term boolean NOT NULL DEFAULT false,
  target_date timestamp with time zone NOT NULL,
  is_completed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 6. HABITS TABLE (Discipline habits & streak history sync)
CREATE TABLE IF NOT EXISTS public.habits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  current_streak integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  last_completed timestamp with time zone,
  completion_history timestamp with time zone[] DEFAULT '{}'::timestamp with time zone[],
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 7. WELLBEING LOGS TABLE (Hydration, Sleep, Mood & Mindfulness check-ins sync)
CREATE TABLE IF NOT EXISTS public.wellbeing_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  water_intake_liters double precision NOT NULL DEFAULT 0.0,
  sleep_duration_hours double precision NOT NULL DEFAULT 0.0,
  mood_rating integer NOT NULL DEFAULT 3,
  mindful_minutes integer NOT NULL DEFAULT 0, -- Ensures complete sync with breathing exercises
  date timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Ensure mindful_minutes column exists if table was previously created
ALTER TABLE public.wellbeing_logs
  ADD COLUMN IF NOT EXISTS mindful_minutes integer NOT NULL DEFAULT 0;

-- 8. SOBRIETY TABLE (Recovery streaks, relapses & urge triggers sync)
CREATE TABLE IF NOT EXISTS public.sobriety (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  sobriety_start_date timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  current_streak_days integer NOT NULL DEFAULT 0,
  longest_streak_days integer NOT NULL DEFAULT 0,
  relapse_dates timestamp with time zone[] DEFAULT '{}'::timestamp with time zone[],
  triggers_log text[] DEFAULT '{}'::text[],
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 9. SCREEN TIMES TABLE (Daily App Blocker usage minutes sync)
CREATE TABLE IF NOT EXISTS public.screen_times (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  package_name text NOT NULL,
  app_name text NOT NULL,
  usage_minutes integer NOT NULL DEFAULT 0,
  date text NOT NULL, -- Format: YYYY-MM-DD
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT screen_times_user_package_date_key UNIQUE (user_id, package_name, date)
);

-- ==============================================================================
-- SAFE MIGRATIONS FOR EXISTING TABLES (Upgrades existing tables if already created)
-- ==============================================================================

-- A. Rename appname to app_name if it exists in screen_times
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='screen_times' AND column_name='appname') THEN
    ALTER TABLE public.screen_times RENAME COLUMN appname TO app_name;
  END IF;
END $$;

-- B. Add unique constraint on screen_times if not already present
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'screen_times_user_package_date_key') THEN
    ALTER TABLE public.screen_times ADD CONSTRAINT screen_times_user_package_date_key UNIQUE (user_id, package_name, date);
  END IF;
END $$;

-- C. Convert GENERATED ALWAYS to GENERATED BY DEFAULT across all tables so Isar IDs can sync without errors
DO $$
DECLARE
  tbl text;
BEGIN
  FOR tbl IN SELECT unnest(ARRAY['focus_sessions', 'tasks', 'habits', 'screen_times', 'sobriety', 'routines', 'goals', 'wellbeing_logs']) LOOP
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=tbl AND column_name='id' AND is_identity='YES' AND identity_generation='ALWAYS') THEN
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET GENERATED BY DEFAULT;', tbl);
    END IF;
  END LOOP;
END $$;

-- D. Add public metrics columns to profiles if not already present
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS streak_days integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS focus_score integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS level integer NOT NULL DEFAULT 1;

-- ==============================================================================
-- PERFORMANCE INDEXES (Speeds up Cloud Sync repository queries by user_id)
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_focus_sessions_user_id ON public.focus_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON public.tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_routines_user_id ON public.routines(user_id);
CREATE INDEX IF NOT EXISTS idx_goals_user_id ON public.goals(user_id);
CREATE INDEX IF NOT EXISTS idx_habits_user_id ON public.habits(user_id);
CREATE INDEX IF NOT EXISTS idx_wellbeing_logs_user_id ON public.wellbeing_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_sobriety_user_id ON public.sobriety(user_id);
CREATE INDEX IF NOT EXISTS idx_screen_times_user_id ON public.screen_times(user_id);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Ensures users can only query, insert, update, or delete their own data
-- ==============================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.focus_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wellbeing_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sobriety ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.screen_times ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
DO $$
BEGIN
  -- Drop restrictive select policy to allow leaderboards
  DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Anyone can view profiles') THEN
    CREATE POLICY "Anyone can view profiles" ON public.profiles FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can update their own profile') THEN
    CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can insert their own profile') THEN
    CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
  END IF;
END $$;

-- Macro Helper Policy Generator for all user_id tables
DO $$
DECLARE
  tbl text;
BEGIN
  FOR tbl IN SELECT unnest(ARRAY['focus_sessions', 'tasks', 'routines', 'goals', 'habits', 'wellbeing_logs', 'sobriety', 'screen_times']) LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = tbl AND policyname = format('Users can view own %s', tbl)) THEN
      EXECUTE format('CREATE POLICY "Users can view own %s" ON public.%I FOR SELECT USING (auth.uid() = user_id);', tbl, tbl);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = tbl AND policyname = format('Users can insert own %s', tbl)) THEN
      EXECUTE format('CREATE POLICY "Users can insert own %s" ON public.%I FOR INSERT WITH CHECK (auth.uid() = user_id);', tbl, tbl);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = tbl AND policyname = format('Users can update own %s', tbl)) THEN
      EXECUTE format('CREATE POLICY "Users can update own %s" ON public.%I FOR UPDATE USING (auth.uid() = user_id);', tbl, tbl);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = tbl AND policyname = format('Users can delete own %s', tbl)) THEN
      EXECUTE format('CREATE POLICY "Users can delete own %s" ON public.%I FOR DELETE USING (auth.uid() = user_id);', tbl, tbl);
    END IF;
  END LOOP;
END $$;

-- 10. ACTIVE STUDY SESSIONS TABLE (Tracks users currently studying in rooms)
CREATE TABLE IF NOT EXISTS public.active_study_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  room_name text NOT NULL,
  joined_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  ends_at timestamp with time zone NOT NULL,
  CONSTRAINT active_study_sessions_user_key UNIQUE (user_id)
);

-- Enable RLS
ALTER TABLE public.active_study_sessions ENABLE ROW LEVEL SECURITY;

-- Add RLS Policies
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'active_study_sessions' AND policyname = 'Anyone can view study sessions') THEN
    CREATE POLICY "Anyone can view study sessions" ON public.active_study_sessions FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'active_study_sessions' AND policyname = 'Users can join study sessions') THEN
    CREATE POLICY "Users can join study sessions" ON public.active_study_sessions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'active_study_sessions' AND policyname = 'Users can leave study sessions') THEN
    CREATE POLICY "Users can leave study sessions" ON public.active_study_sessions FOR DELETE TO authenticated USING (auth.uid() = user_id);
  END IF;
END $$;
